{{- if not .Values.database.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "puppy-store.fullname" . }}-db-secret
  labels:
    {{- include "puppy-store.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation
type: Opaque
stringData:
  password: {{ .Values.database.password | default "postgres" | quote }}
{{- end }}
