apiVersion: v1
kind: Secret
metadata:
  name: {{ include "puppy-store.fullname" . }}-jwt-secret
  labels:
    {{- include "puppy-store.labels" . | nindent 4 }}
type: Opaque
data:
  secret: {{ .Values.jwt.secret | b64enc | quote }}
