apiVersion: v1
kind: Service
metadata:
  name: {{ include "puppy-store.fullname" . }}-auth
  labels:
    {{- include "puppy-store.labels" . | nindent 4 }}
    app.kubernetes.io/component: auth
spec:
  type: {{ .Values.auth.service.type }}
  ports:
    - port: {{ .Values.auth.service.port }}
      targetPort: {{ .Values.auth.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "puppy-store.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: auth
