{{- if .Values.redis.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "puppy-store.fullname" . }}-redis
  labels:
    {{- include "puppy-store.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.redis.service.port }}
      targetPort: 6379
      protocol: TCP
      name: redis
  selector:
    {{- include "puppy-store.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: redis
{{- end }}
