apiVersion: v1
kind: Service
metadata:
  name: {{ include "puppy-store.fullname" . }}-chat
  labels:
    {{- include "puppy-store.labels" . | nindent 4 }}
    app.kubernetes.io/component: chat
spec:
  type: {{ .Values.chat.service.type }}
  ports:
    - port: {{ .Values.chat.service.port }}
      targetPort: {{ .Values.chat.service.targetPort }}
      protocol: TCP
      name: ws
  selector:
    {{- include "puppy-store.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: chat
